version: '3.8'

services:
  postgres:
    container_name: postgres4Satellearth
    build:
      context: .
      dockerfile: Dockerfile-db.txt
    environment:
      POSTGRES_USER: ${SATELLEARTH_API_DB_USER}
      POSTGRES_PASSWORD: ${SATELLEARTH_API_DB_PASSWORD}
      POSTGRES_DB: ${SATELLEARTH_API_DB_NAME}
    ports:
      - "1234:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
      - ./backup.dump:/backup.dump:ro
    networks:
      - current-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4Satellearth
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  current-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:
