name: Deploy to Server

on:
  push:
    branches:
      - main  #Push on main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Node.js version needed by the project

    # 3. Install dependancies
    - name: Install dependencies
      run: npm install

    # 4. Build Nest project
    - name: Build Nest project
      run: npm run build

    # 5. Add SSH key for connection
    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known_hosts
      run: |
        ssh-keyscan -H ec2-13-36-38-31.eu-west-3.compute.amazonaws.com >> ~/.ssh/known_hosts

    # 6. Déployer le dossier dist sur le serveur
    - name: Deploy to server
      run: |
        scp -r ./dist root@ec2-13-36-38-31.eu-west-3.compute.amazonaws.com:/opt/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
